/*-------------------------------------------------------------------------
 *
 * kwlist.h
 *
 * The keyword lists are kept in their own source files for use by
 * automatic tools.  The exact representation of a keyword is determined
 * by the PG_KEYWORD macro, which is not defined in this file; it can
 * be defined by the caller for special purposes.
 *
 * Portions Copyright (c) 1996-2022, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * IDENTIFICATION
 *	  src/include/parser/kwlist.h
 *
 *-------------------------------------------------------------------------
 */

/* there is deliberately not an #ifndef KWLIST_H here */

/*
 * List of keyword (name, token-value, category, bare-label-status) entries.
 *
 * Note: gen_keywordlist.pl requires the entries to appear in ASCII order.
 */

/* name, value, category, is-bare-label */
/* PG_KEYWORD("abort", ABORT_P, UNRESERVED_KEYWORD, BARE_LABEL) */
PG_KEYWORD("and",AND,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("beans",BEANS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("bufferedinputstream",BUFFEREDINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("bufferedreader",BUFFEREDREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("bytearrayinputstream",BYTEARRAYINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("bytearrayoutputstream",BYTEARRAYOUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("chararrayreader",CHARARRAYREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("class",CLASS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("classloader",CLASSLOADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("collections",COLLECTIONS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("command",COMMAND,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("compiler",COMPILER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("content",CONTENT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("context",CONTEXT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("datainputstream",DATAINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("debug",DEBUG,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("default_member_access",DEFAULT_MEMBER_ACCESS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("entitymanager",ENTITYMANAGER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("expression",EXPRESSION,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("file",FILE_P,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filedescriptor",FILEDESCRIPTOR,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("fileinputstream",FILEINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("fileoutputstream",FILEOUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filepermission",FILEPERMISSION,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filereader",FILEREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filewriter",FILEWRITER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filterinputstream",FILTERINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filteroutputstream",FILTEROUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("filterreader",FILTERREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("inheritablethreadlocal",INHERITABLETHREADLOCAL,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("inputstream",INPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("inputstreamreader",INPUTSTREAMREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("integer",INTEGER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("io",IO,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("java",JAVA,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("javax",JAVAX,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("lang",LANG,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("linenumberreader",LINENUMBERREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("memberaccess",MEMBERACCESS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("message",MESSAGE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("misc",MISC,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("new",NEW,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("not",NOT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("number",NUMBER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("object",OBJECT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("objectoutputstream",OBJECTOUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("ognl",OGNL,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("ognlcontext",OGNLCONTEXT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("or",OR,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("outputstream",OUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("package",PACKAGE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("persistence",PERSISTENCE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("pipedoutputstream",PIPEDOUTPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("pipedreader",PIPEDREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("printstream",PRINTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("process",PROCESS,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("processbuilder",PROCESSBUILDER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("pushbackinputstream",PUSHBACKINPUTSTREAM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("reader",READER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("reflect",REFLECT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("runtime",RUNTIME,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("runtimepermission",RUNTIMEPERMISSION,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("scanner",SCANNER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("script",SCRIPT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("scriptenginemanage",SCRIPTENGINEMANAGE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("securitymanager",SECURITYMANAGER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("servlet",SERVLET,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("servletcontext",SERVLETCONTEXT,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("shutdown",SHUTDOWN,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("string",STRING,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("stringbuilder",STRINGBUILDER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("stringreader",STRINGREADER,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("sun",SUN,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("system",SYSTEM,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("thread",THREAD,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("threadgroup",THREADGROUP,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("threadlocal",THREADLOCAL,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("type",TYPE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("unsafe",UNSAFE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("util",UTIL,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("xmldecode",XMLDECODE,UNRESERVED_KEYWORD,BARE_LABEL)
PG_KEYWORD("xor",XOR,UNRESERVED_KEYWORD,BARE_LABEL)

